### ISSUE TITLE
Generated file name conflict

### ISSUE THREAD

**Issue by barryrowlingson** [the-y-company/many#7]
If you have a file `srcpkg/data-file.R` and a file `file.R` in a folder `srcpkg/data` then these get mapped to the same filename in the built `R` folder:

```
> bundle()
── many: bundling 
✔ COPIED:    srcpkg/data-file.R copied to R/data-file.R
✔ COPIED:    srcpkg/data/file.R copied to R/data-file.R
✔ COPIED:    srcpkg/file.R copied to R/file.R
```

There doesn't appear to be any warning, just any functions defined in the first file copied will not exist in the built package.

**Comment by JohnCoene** [comment]
Ah yes, since I expand the path and replace `/` with `-` that can cause clashes.

I had not thought of that, going to have to think of a fix.

**Comment by JohnCoene** [comment]
Thanks again for reporting this issue.

This should be fixed now, it's a bit of a cheap trick (see below), if you have a more elegant solution please feel free to share it.

https://github.com/the-y-company/many/blob/18d015322a700fe13bf7c9e649840339e41f72bd/srcpkg/utils.R#L25

If you have an ongoing project you want to run `many::reset()`.

**Comment by JohnCoene** [comment]
I'm going to close since I think the issue has been tackled, feel free to reopen if it was not.
Thanks again for reporting it.
